---
# tasks file for cloudera

- name: Config Environment
  include_role: 
    name: cm-env-setup

- name: Setup repository
  include_role:
    name: cm-repo

- name: Install Oracle Java
  include_role:
    name: oracle-java-8u144-tgz

- name: Install Cloudera Manager with Path B
  include_role:
    name: cm-install-path-b

- name: Wait for cloudera to start up before proceeding.
  shell: "curl -D - --silent --max-time 5 http://localhost:7180/cmf"
  register: result
  until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
  retries: "60"
  delay: "10"
  changed_when: false
  check_mode: no
