---
# tasks file for cm-repo

- name: Add Cloudera Manager yum repo
  yum_repository:
    name: cloudera-manager
    description: Cloudera Manager
    baseurl: https://archive.cloudera.com/cm5/redhat/7/x86_64/cm/5.13/
    gpgkey: https://archive.cloudera.com/cm5/redhat/7/x86_64/cm/RPM-GPG-KEY-cloudera
    gpgcheck: yes
    enabled: yes
