---

- name: Unlock process and open file number for cloudera users
  lineinfile:
    path: /etc/security/limits.conf
    line: '{{ item }}'
  with_items:
    - hdfs - nofile 32768
    - mapred - nofile 32768
    - hbase - nofile 32768
    - hdfs - nproc 32768
    - mapred - nproc 32768
    - hbase - nproc 32768
    - cloudera-scm - nproc 32768
    - cloudera-scm - nofile 32768
    - kudu - nproc 32768
    - kudu - nofile 32768
    - hue - nproc 32768
    - hue - nofile 32768
